### ISSUE TITLE
Waitlist signup tracking issue

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1307]
- [x] metalbear-co/mirrord#1303 
- [x] metalbear-co/mirrord#1306 
- [x] metalbear-co/mirrord-intellij#77
