### ISSUE TITLE
Next-protocol tracking

### ISSUE THREAD

**Issue by aviramha** [metalbear-co/mirrord#1353]
This issue is for tracking the "next" protocol for mirrord-agent/operator/layer/proxy.

We want to make the transition as easy as possible with least breaking between versions.

The list is WIP and follow up on https://github.com/metalbear-co/operator/issues/110

- [x] #1354
- [ ] #1356
- [ ] Add IDs to messages to match request/response
- [ ] Parallel handling (blocked on IDs)
- [x] #1355
- [x] Add CI for protocol breaking warning to bump versions when needed (backward/forward compatible)
